name: Go CI (Deprecated)

on: [] # Empty array means this will never trigger automatically

jobs:
  deprecated:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow has been replaced by backend-ci.yml and frontend-ci.yml. Delete this file later."
